# version: '3.8'

services:
  backend:
    build:
      context: ./backend
      # dockerfile: Dockerfile.backend
    # command: sh /django/entrypoint.sh
    volumes:
      - static_volume:/django/staticfiles
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: server.settings

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      # - ./nginx/nginx-setup.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/client
      - static_volume:/var/www/static
    depends_on:
      - backend
      - frontend

  # frontend:
  #   build:
  #     context: ./frontend
  #   volumes:
  #     - react_build:/build
  #   depends_on:
  #     - backend


  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/client/build
    depends_on:
      - backend

volumes:
  react_build:
  static_volume:
